// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpbbxhuvrklwpewcsgvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwYmJ4aHV2cmtsd3Bld2NzZ3Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3NDk2MjEsImV4cCI6MjA2NzMyNTYyMX0.n78PJj26N-_PtXwj9YI6Dfhn47qKMps7YH1A0y3-9h8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});